# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['maincode.py'],
    pathex=[r'C:\Users\Dany\python_c++\виселица'],
    binaries=[],
    datas=[(r'images/виселица2.png', 'images'),
    (r'images/виселица3.png', 'images'),
    (r'images/виселица4.png', 'images'),
    (r'images/виселица5.png', 'images'),
    (r'images/виселица6.png', 'images'),
    (r'images/виселица7.png', 'images'),
    (r'images/виселица8.png', 'images'),
    (r'images/виселица9.png', 'images'),
    (r'images/виселица10.png', 'images'),
    (r'images/виселица11.png', 'images'),
    (r'images/громкость.png', 'images'),
    (r'images/громкость_зачеркнт.png', 'images'),
    (r'images/главное_меню.png', 'images'),
    (r'images/победа3.png', 'images'),
    (r'images/поражение3.png', 'images'),
    (r'fonts/arial.ttf', 'fonts'),
    (r'texts/russian_nouns.txt', "texts"),
    (r'images/правли2.png', 'images'),
    (r'music/буква_неугадана.mp3', 'music'),
    (r'music/главное_меню.mp3', 'music'),
    (r'music/победа.mp3', 'music'),
    (r'music/поражение2.mp3', 'music'),
    (r'music/угадал_букву.mp3', 'music'),
    (r'texts/easy', 'texts'),
    (r'texts/normal', 'texts'),
    (r'texts/hardcore', 'texts')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Viselitsa-reliz',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['C:\\Users\\Dany\\python_c++\\виселица\\иконка.ico'],
)
